const CHANGE_CURRENT_SCREEN = 'CHANGE_CURRENT_SCREEN';
const GO_TO_PREVIOUS_SCREEN = 'GO_TO_PREVIOUS_SCREEN';
const CHANGE_HEADER_VISIBILITY = 'CHANGE_HEADER_VISIBILITY';

export default {
  CHANGE_CURRENT_SCREEN,
  GO_TO_PREVIOUS_SCREEN,
  CHANGE_HEADER_VISIBILITY,
};
