// const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
// const SET_USER_LOGGED_OUT = 'SET_USER_LOGGED_OUT';
// const USER_LOGGED_IN_FAIL = 'USER_LOGGED_IN_FAIL';
// const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';

// export default {
//   SET_USER_LOGGED_IN,
//   SET_USER_LOGGED_OUT,
//   USER_LOGGED_IN_FAIL,
//   CLEAR_ERROR_MESSAGE,
// };

const START_SIGN_IN_ACTION = 'START_SIGN_IN_ACTION';
const SUCCESS_SIGN_IN_ACTION = 'SUCCESS_SIGN_IN_ACTION';
const FAIL_SIGN_IN_ACTION = 'FAIL_SIGN_IN_ACTION';

const START_SIGN_OUT_ACTION = 'START_SIGN_OUT_ACTION';
const SUCCESS_SIGN_OUT_ACTION = 'SUCCESS_SIGN_OUT_ACTION';
const FAIL_SIGN_OUT_ACTION = 'FAIL_SIGN_OUT_ACTION';

export default {
  START_SIGN_IN_ACTION,
  SUCCESS_SIGN_IN_ACTION,
  FAIL_SIGN_IN_ACTION,

  START_SIGN_OUT_ACTION,
  SUCCESS_SIGN_OUT_ACTION,
  FAIL_SIGN_OUT_ACTION,
};
