const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
const SET_USER_LOGGED_OUT = 'SET_USER_LOGGED_OUT';
const USER_LOGGED_IN_FAIL = 'USER_LOGGED_IN_FAIL';
const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';

export default {
  SET_USER_LOGGED_IN,
  SET_USER_LOGGED_OUT,
  USER_LOGGED_IN_FAIL,
  CLEAR_ERROR_MESSAGE,
};
