const START_SIGN_IN_ACTION = 'START_SIGN_IN_ACTION';
const SUCCESS_SIGN_IN_ACTION = 'SUCCESS_SIGN_IN_ACTION';
const FAIL_SIGN_IN_ACTION = 'FAIL_SIGN_IN_ACTION';

const START_SIGN_OUT_ACTION = 'START_SIGN_OUT_ACTION';
const SUCCESS_SIGN_OUT_ACTION = 'SUCCESS_SIGN_OUT_ACTION';
const FAIL_SIGN_OUT_ACTION = 'FAIL_SIGN_OUT_ACTION';

export default {
  START_SIGN_IN_ACTION,
  SUCCESS_SIGN_IN_ACTION,
  FAIL_SIGN_IN_ACTION,

  START_SIGN_OUT_ACTION,
  SUCCESS_SIGN_OUT_ACTION,
  FAIL_SIGN_OUT_ACTION,
};
