const START_LOADING_QUESTIONS = 'START_LOADING_QUESTIONS';
const SUCCESS_LOADING_QUESTIONS = 'SUCCESS_LOADING_QUESTIONS';
const FAIL_LOADING_QUESTIONS = 'FAIL_LOADING_QUESTIONS';

export default {
  START_LOADING_QUESTIONS,
  SUCCESS_LOADING_QUESTIONS,
  FAIL_LOADING_QUESTIONS,
};
